import { BsFiletypeHtml, BsFiletypeCss, BsBootstrap, BsFiletypeXml } from "react-icons/bs";
import { FaNodeJs } from "react-icons/fa";
import {
  SiJavascript,
  SiReact,
  SiAdobephotoshop,
  SiMongodb,
  SiMysql,
  SiGithub,
  SiExpress,
  SiDart,
  SiFlutter,
} from "react-icons/si";

export const TechstackList = [
  {
    _id: 1,
    name: "HTML",
    icon: BsFiletypeHtml,
    gradientFrom: 'orange',
    gradientTo: 'red',
  },
  {
    _id: 2,
    name: "CSS / SCSS",
    icon: BsFiletypeCss,
    gradientFrom: 'blue',
    gradientTo: 'cyan',
  },
  {
    _id: 3,
    name: "Bootstrap",
    icon: BsBootstrap,
    gradientFrom: 'grape',
    gradientTo: 'violet',
  },
  {
    _id: 4,
    name: "Javascript",
    icon: SiJavascript,
    gradientFrom: 'yellow',
    gradientTo: 'orange',
  },
  {
    _id: 5,
    name: "React JS",
    icon: SiReact,
    gradientFrom: 'cyan',
    gradientTo: 'teal',
  },
  {
    _id: 6,
    name: "Photoshop",
    icon: SiAdobephotoshop,
    gradientFrom: 'indigo',
    gradientTo: 'blue',
  },
  {
    _id: 7,
    name: "Node JS",
    icon: FaNodeJs,
    gradientFrom: 'lime',
    gradientTo: 'green',
  },
  {
    _id: 8,
    name: "Express JS",
    icon: SiExpress,
    gradientFrom: 'gray',
    gradientTo: 'dark',
  },
  {
    _id: 9,
    name: "Mongodb",
    icon: SiMongodb,
    gradientFrom: 'teal',
    gradientTo: 'green',
  },
  {
    _id: 10,
    name: "SQL",
    icon: SiMysql,
    gradientFrom: 'blue',
    gradientTo: 'indigo',
  },
  {
    _id: 11,
    name: "Git / Github",
    icon: SiGithub,
    gradientFrom: 'dark',
    gradientTo: 'black',
  },
  {
    _id: 12,
    name: "XML",
    icon: BsFiletypeXml,
    gradientFrom: 'orange',
    gradientTo: 'yellow',
  },
  {
    _id: 13,
    name: "Dart",
    icon: SiDart,
    gradientFrom: 'cyan',
    gradientTo: 'blue',
  },
  {
    _id: 14,
    name: "Flutter",
    icon: SiFlutter,
    gradientFrom: 'blue',
    gradientTo: 'teal',
  },
];